/**:
  ros__parameters:
    feature_extract_enable: false
    point_filter_num: 2
    max_iteration: 4
    filter_size_surf: 0.2
    filter_size_map: 0.2
    cube_side_length: 200.0
    runtime_pos_log_enable: false
    map_file_path: "PCD/gigaai_airy_rear_map.pcd" # Can be overridden by the launch argument.

    common:
      lid_topic: "/rslidar_rear/points"
      imu_topic: "/rslidar_rear/imu_data"
      time_sync_en: false
      time_offset_lidar_to_imu: 0.0
      imu_gyr_unit: "rad"

    preprocess:
      lidar_type: 5 # 5: airy96
      scan_line: 96
      timestamp_unit: 0 # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
      blind: 0.0
      scan_rate: 10

    mapping:
      max_search_dist_surf: 1.0
      num_sub_cloud: 1
      acc_cov: 0.1
      gyr_cov: 0.1
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      fov_degree: 120.0
      det_range: 200.0
      extrinsic_est_en: false
      extrinsic_T: [0.00425, 0.00418, -0.00446]
      extrinsic_R: [
        -0.0019456169, -0.9998835668,  0.0151349759,
        -0.9999936477,  0.0019905860,  0.0029567054,
        -0.0029864886, -0.0151291271, -0.9998810881
      ]

    publish:
      path_en: true
      effect_map_en: false
      map_en: false
      scan_publish_en: true
      dense_publish_en: true
      scan_bodyframe_pub_en: true

    pcd_save:
      pcd_save_en: true
      interval: -1
