/**:
  ros__parameters:
    feature_extract_enable: false
    point_filter_num: 1
    max_iteration: 3
    filter_size_surf: 0.1
    filter_size_map: 0.1
    cube_side_length: 1000.0
    runtime_pos_log_enable: false
    map_file_path: "PCD/mid360_map.pcd"

    common:
      lid_topic: "/livox/custom_msg"
      imu_topic: "/livox/imu"
      time_sync_en: false
      time_offset_lidar_to_imu: 0.0
      imu_gyr_unit: "rad"

    preprocess:
      lidar_type: 11 # 11: mid360
      scan_line: 4
      timestamp_unit: 3 # Livox CustomMsg offset_time is ns; handler outputs ms internally.
      scan_rate: 10
      blind: 0.5

    mapping:
      acc_cov: 0.1
      gyr_cov: 0.1
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      fov_degree: 360.0
      det_range: 100.0
      extrinsic_est_en: false
      extrinsic_T: [-0.011, -0.02329, 0.04412]
      extrinsic_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

    publish:
      path_en: true
      map_en: true
      scan_publish_en: true
      dense_publish_en: true
      effect_map_en: false
      scan_bodyframe_pub_en: false

    pcd_save:
      pcd_save_en: true
      interval: -1
